### ISSUE TITLE
Starting Work On Tokenization module . 

### ISSUE THREAD

**Issue by jaideepkekre** [jaideepkekre/MediBot#1]
@v0dro  You're inputs ?

**Comment by jaideepkekre** [comment]
@v0dro You're inputs ?

**Comment by v0dro** [comment]
Just use nltk :P

I'll need to look this up before commenting.

**Comment by jaideepkekre** [comment]
Not going to use NLTK , it will do our job in seconds .  I'm making my own tokenization module . Classification in something we need to discuss . We need a learning classifier . 
As far as possible i want to use our code , not libs . Libs can be used but as a last resort or if we are lazy . 

@v0dro

**Comment by v0dro** [comment]
Why reinvent the wheel :\

**Comment by jaideepkekre** [comment]
@v0dro Well tokenization is a small thing . i want to it myself . NLTK is a big library , we don't need it . If in future we do , i'll shift it . The NLP module is mine so all i have to do is give you a dict with tokenized works and classify the works in the next module .

**Comment by jaideepkekre** [comment]
Highly irrelevant  as we have pivoted away from NLP . In hindsight , not using NLTK was a good idea.
