### ISSUE TITLE
ImportError: cannot import name 'Updater'

### ISSUE THREAD

**Issue by rexwulf** [jaideepkekre/MediBot#21]
`./run.sh
Traceback (most recent call last):
  File "/Users/rex/Downloads/MediBot-master/bin/server.py", line 11, in <module>
    from telegram import Updater
ImportError: cannot import name 'Updater'`

I've updated telegram but still unable to resolve this issue.

**Comment by jaideepkekre** [comment]
This seems to be because telegram has updated their library structure. 
In the short term, there are no plans to fix this on my side. You can submit a pull request with fix.
