### ISSUE TITLE
Threading 

### ISSUE THREAD

**Issue by jaideepkekre** [jaideepkekre/MediBot#3]
## 1. Let's do this , each user gets a thread .
- Text/dict from user is kept in queue , the thread consumes text / dict and only consumes next text/dict after previous request has returned . 
## 2. Let's do this , each NLP op gets a thread .
- each NLP op in core.py gets a thread as NLP will be the heaviest job in our code .
## What's your opinion ?

@v0dro

**Comment by v0dro** [comment]
I think we'll go with option 1.

NLP threading can be later as and when required, depending on what operations turn out to be the slowest.
