### ISSUE TITLE
Formalize JSON format for database

### ISSUE THREAD

**Issue by v0dro** [jaideepkekre/MediBot#4]
@jaideepkekre list your thoughts about the json format to be used for DB storage here.

I'll put up a mock from my side in a short time.

**Comment by v0dro** [comment]
Ok so here's a brain dump:

For the MVP, we'll go with not supporting time based symptom recognition, instead only go for the simplest case where the patient has certain symptoms and the system tries to elicit a response from the patient based on successive symptoms that he reports, and tries to figure out what the patient is suffering from.

Say we have 2 database stores: One that stores `disease -> symptom` pairs and the other that stores `symptom synonyms -> symptom` pairs.

The ES should be able to figure out a disease based on the symptoms reported by the patient or any synonyms of the disease that are found in the sentence.

For example, given the sentence `I think I am running a temperature`, the NLP engine should be able to figure out that `running a temperature` translates to `fever`, and send the appropriately marked dict to the ES.

Keep in mind that the ES should only receive the actual symptoms for a particular disease. For example, the way `bro i think i'm running a temperature` can be marked up as a dict which looks like:

``` python

{
 'symptom' : 'fever', 
 # more things necessary to be sent.
}

```

**Comment by jaideepkekre** [comment]
Ok. You need to call me up asap , so i can get started on the obo parser .

**Comment by jaideepkekre** [comment]
I think we have resolved this . Please close if satisfied
