### ISSUE TITLE
Use simple in-memory data store intead of dispatcher

### ISSUE THREAD

**Issue by v0dro** [jaideepkekre/MediBot#7]
Since the message queuing architecture is now multi-process, it does not seem necessary to stilll have the dispatcher around. One process manages getting and queuing messages and the other processes them and sends them across.

Using an  in-memory data store like Redis to store the messages of a conversation would be simpler and cleaner. The core class can simply read the the `chat_id` and pull the relevant conversation.

**Comment by jaideepkekre** [comment]
No , we need logical differentiation of each module . Don't attempt to merge the dispatching functionality at this moment . Let things settle for a bit , let the first NLP queries start . 

If we get a performance boot by using your idea we will surely implement it . So will we ?
