### ISSUE TITLE
Formalize format for storing patient attributes

### ISSUE THREAD

**Issue by v0dro** [jaideepkekre/MediBot#8]
Storing information on the patient will require another schema. Discuss here.

**Comment by jaideepkekre** [comment]
We will need two schemas .
1.Patient Common data 
2.Patient Medical data

**Comment by v0dro** [comment]
Common data? Age, sex, etc?

**Comment by jaideepkekre** [comment]
Common data : age , sex ,weight etc 
Medical data : data from our NLP

**Comment by v0dro** [comment]
Common data ->
- name
- age
- sex
- locality
- weight
- height

Medical data ->
- symptoms
- possible disease
- number  of other people with similar symptoms in locality

@jaideepkekre

**Comment by jaideepkekre** [comment]
We will use the medical data independently (anonymously)  to crowd source the disease symptoms and GPS co-ordinates .

**Comment by v0dro** [comment]
According to our recent conversation, I'm coming up with a very basic conversation for creating said schemas and deciding data flows:

```
user -> I have a fever.
bot -> Hello, you seem new. Before we diagnose your fever, can you please tell us your name?
user -> Jaideep
bot -> Alright Jaideep. Whats your age and gender?
user -> 25
user -> Male
bot -> What is your address?
user ->  Pune. magchya gallit.
bot -> Alright Jaideep. We have enough info on you. Can you please tell us what ails you?
user -> I got fever man!
bot -> Can you use a thermometer and tell us your temperature?
user -> 103
bot -> Are you experiencing body pains?
user -> yes a little too much
bot -> What is the color of your urine?
user -> Dark Yellow
bot -> Do you have bleeding gums?
user -> no
bot -> Alright jaideep, we have enough information on you for now. Please visit Dr. Sameer Deshmukh ASAP. You are in deep shit.
```

Something needs to indicate an 'intent' for starting a conversation. Right now it's a sentence that indicates the user showing a particular symptom. So now the user with a particular chat_id has not registered his name with the bot, so he is asked for it. So once the basic user info is in place, only then does the actual conversation for gathering data about diseases and symptoms start.This sort of symptom (as in which has a variable answer, and which needs to be asked in a specially crafted sentence) will need some clever schema magic.

@jaideepkekre neet vachun ghe

**Comment by jaideepkekre** [comment]
I think we have resolved this . Please close if satisfied
